name: Main Deploy

on:
  workflow_run:
    workflows: ["Backend CI/CD", "Frontend CI/CD"]
    types:
      - completed
  workflow_dispatch: # Allows you to run it manually from GitHub UI

jobs:
  deploy-to-server:
    # Only run if the previous build workflow actually succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Update Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/api-simulator
            # Pull the latest versions of both images
            docker compose -f docker-compose.prod.yml pull
            
            # Restart the services without downtime
            docker compose -f docker-compose.prod.yml up -d
            
            # Clean up old unused images to save space
            docker image prune -f
